name: Deploy Hugging Face Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up HF credentials
        run: |
          git config --global user.email "${{ secrets.HF_USERNAME }}@users.noreply.huggingface.co"
          git config --global user.name "${{ secrets.HF_USERNAME }}"
          git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.SPACE_NAME }} hf_space
          rm -rf hf_space/*
          cp -r backend/* hf_space/
          cd hf_space
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes to commit"
          git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ secrets.HF_USERNAME }}/${{ secrets.SPACE_NAME }} main

